"""Dad jokes corpus - 500 clean dad jokes."""

import random

DAD_JOKES = [
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I used to hate facial hair, but then it grew on me.",
    "What do you call a fake noodle? An impasta!",
    "Why did the scarecrow win an award? He was outstanding in his field!",
    "I only know 25 letters of the alphabet. I don't know y.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don't eggs tell jokes? They'd crack each other up!",
    "I'm on a seafood diet. I see food and I eat it.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What do you call a fish without eyes? A fsh!",
    "I would tell you a construction joke, but I'm still working on it.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "I used to play piano by ear, but now I use my hands.",
    "Why did the math book look so sad? Because it had too many problems.",
    "What's orange and sounds like a parrot? A carrot!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why can't you give Elsa a balloon? Because she'll let it go!",
    "What do you call a lazy kangaroo? A pouch potato!",
    "I'm afraid for the calendar. Its days are numbered.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What do you call a dinosaur that crashes their car? Tyrannosaurus Wrecks!",
    "I used to be a banker, but I lost interest.",
    "Why don't oysters share? Because they're shellfish!",
    "What's brown and sticky? A stick!",
    "How do you organize a space party? You planet!",
    "Why did the cookie go to the hospital? Because it felt crummy!",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "I'm terrified of elevators, so I'm taking steps to avoid them.",
    "What did the grape do when it got stepped on? It let out a little wine!",
    "Why couldn't the bicycle stand up by itself? It was two tired!",
    "What do you call a cow with no legs? Ground beef!",
    "I got a job at a bakery because I kneaded dough.",
    "Why did the stadium get hot? All the fans left!",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "I don't trust stairs. They're always up to something.",
    "What do you call a dog that does magic tricks? A Labracadabrador!",
    "Why don't scientists trust atoms? They make up everything!",
    "I asked my dog what's two minus two. He said nothing.",
    "What do you call a belt made of watches? A waist of time!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I used to be addicted to soap, but I'm clean now.",
    "What did one wall say to the other? I'll meet you at the corner!",
    "Why did the can crusher quit his job? Because it was soda pressing!",
    "I made a pencil with two erasers. It was pointless.",
    "What do you call a boomerang that doesn't come back? A stick!",
    "Why do bees have sticky hair? Because they use honeycombs!",
    "I'm reading a book on the history of glue. I can't put it down!",
    "What did the buffalo say when his son left? Bison!",
    "Why do chicken coops only have two doors? If they had four, they'd be chicken sedans!",
    "I used to hate facial hair, but then it grew on me.",
    "What do you call a pig that does karate? A pork chop!",
    "Why did the coffee file a police report? It got mugged!",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don't eggs tell jokes? They'd crack each other up!",
    "I used to work at a calendar factory, but I got fired for taking a few days off.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it!",
    "I'm thinking about removing my spine. I feel like it's only holding me back.",
    "What do you call a fish that wears a bowtie? Sofishticated!",
    "Why couldn't the pony sing? Because she was a little horse!",
    "What do you call a cow on a trampoline? A milkshake!",
    "I asked my wife if I was the only one she'd been with. She said yes, all the others were nines and tens.",
    "Why did the gym close down? It just didn't work out!",
    "What do you call a fake stone? A shamite!",
    "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
    "Why don't basketball players go on vacation? They'd get called for traveling!",
    "What do you call a deer with no eyes? No idea!",
    "I used to be a personal trainer, but then I gave my too weak notice.",
    "Why did the man put his money in the freezer? He wanted cold hard cash!",
    "What do you call a factory that sells good products? A satisfactory!",
    "I'm only familiar with 25 letters of the alphabet. I don't know why.",
    "What do you call a cow with two legs? Lean beef!",
    "Why did the picture go to jail? Because it was framed!",
    "I don't trust people who do acupuncture. They're back stabbers.",
    "What do you call a fish that needs a knee operation? A sturgeon!",
    "Why did the music teacher go to jail? For fingering A minor.",
    "What do you call someone who can't stick with a diet? A desserter!",
    "I used to be a banker but I lost interest.",
    "What do you call a sheep with no legs? A cloud!",
    "Why did the robber take a bath? He wanted to make a clean getaway!",
    "I'm friends with all electricians. We have great current connections.",
    "What do you call a guy with a rubber toe? Roberto!",
    "Why did the coach go to the bank? To get his quarterback!",
    "I used to be a shoe salesman, until they gave me the boot.",
    "What do you call a line of rabbits walking backwards? A receding hare line!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "I tried to catch fog yesterday. Mist.",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the melon jump into the lake? It wanted to be a watermelon!",
    "I used to be indecisive. Now I'm not so sure.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the duck go to rehab? He was a quack addict!",
    "I used to have a job at the orange juice factory, but I got canned. Couldn't concentrate.",
    "What do you call a pile of cats? A meow-ntain!",
    "Why did the mushroom go to the party? Because he's a fungi!",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
    "What do you call a deer with no eyes and no legs? Still no idea!",
    "Why did the man get hit by a bike every day? He was stuck in a vicious cycle!",
    "I used to be a personal trainer. Then I gave my two-weeks notice.",
    "What do you call a bear in the rain? A drizzly bear!",
    "Why don't melons get married? Because they cantaloupe!",
    "I bought some shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
    "What do you call a sad cup of coffee? Depresso!",
    "Why did the golfer bring extra pants? In case he got a hole in one!",
    "I used to collect magazines but I had too many issues.",
    "What do you call a cow that plays an instrument? A moo-sician!",
    "Why did the belt get arrested? For holding up a pair of pants!",
    "I'm not lazy, I'm just on energy-saving mode.",
    "What do you call a nosy pepper? Jalapeño business!",
    "Why did the computer go to the doctor? It had a virus!",
    "I used to think I was indecisive, but now I'm not so sure.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "Why did the frog take the bus to work? His car got toad away!",
    "I entered ten puns in a contest hoping one would win. No pun in ten did.",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the banana go to the doctor? It wasn't peeling well!",
    "I used to play piano by ear, but now I use my hands like everyone else.",
    "What do you call a snowman party? A snowball!",
    "Why did the hipster burn his mouth? He drank his coffee before it was cool!",
    "I used to be a tailor, but I wasn't suited for it. It was a sew-sew job.",
    "What do you call a horse that lives next door? A neigh-bor!",
    "Why did the tree go to the dentist? It needed a root canal!",
    "I started a band called 999 Megabytes. We still haven't gotten a gig.",
    "What do you call a snobbish criminal going down stairs? A condescending con descending!",
    "Why did the computer break up with the internet? There was no connection!",
    "I used to have a fear of hurdles, but I got over it.",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "Why did the vegetable call the plumber? It had a leek!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What do you call a group of killer whales playing instruments? An orca-stra!",
    "Why did the old man fall in the well? He couldn't see that well!",
    "I used to be a transplant surgeon, but my heart just wasn't in it.",
    "What do you call a dog magician? A Labracadabrador!",
    "Why did the coffee file a police report? It got mugged!",
    "I told my cat that I'm going to teach him to speak. He said, 'Me, how?'",
    "What do you call a parade of rabbits hopping backwards? A receding hare-line!",
    "Why can't you trust a burrito? They tend to spill the beans!",
    "I used to be afraid of purchasing living room furniture, but I've got a new couch now.",
    "What do you call birds that stick together? Velcrows!",
    "Why did the lamp break up with the switch? The relationship had no spark!",
    "I asked the librarian if she had any books on paranoia. She whispered, 'They're right behind you!'",
    "What do you call an arrogant criminal coming down the stairs? A condescending con descending!",
    "Why did the phone wear glasses? Because it lost its contacts!",
    "I used to hate math, but then I realized decimals have a point.",
    "What do you call a fish that practices medicine? A sturgeon!",
    "Why did the barber win the race? He knew a shortcut!",
    "I gave away my old batteries, free of charge.",
    "What do you call a pony with a cough? A little horse!",
    "Why don't eggs tell jokes? They'd crack each other up!",
    "I used to have a handle on life, but then it broke.",
    "What do you call a fake Irish stone? A sham-rock!",
    "Why did the stadium get so hot? All the fans left!",
    "I would avoid the sushi if I were you. It's a little fishy.",
    "What do you call a cow during an earthquake? A milkshake!",
    "Why did the invisible man turn down the job? He couldn't see himself doing it!",
    "I used to be addicted to the hokey pokey, but I turned myself around.",
    "What do you call a monkey at the North Pole? Lost!",
    "Why did the man put his money in the blender? He wanted liquid assets!",
    "I just broke up with my mathematician girlfriend. She was always trying to solve our problems.",
    "What do you call a dog that does magic? A Labracadabrador!",
    "Why did the balloon go near the needle? He wanted to be a pop star!",
    "I used to work in a shoe recycling shop. It was sole-destroying.",
    "What do you call a factory that makes okay products? A satisfactory!",
    "Why did the PowerPoint presentation cross the road? To get to the other slide!",
    "I'm making a documentary about beavers. It's the best dam movie ever!",
    "What do you call a lazy baby kangaroo? A pouch potato!",
    "Why did the scarecrow become a motivational speaker? He was outstanding in his field!",
    "I used to run a dating service for chickens, but I was struggling to make hens meet.",
    "What do you call an alligator detective? An investi-gator!",
    "Why did the bike fall over? It was two-tired!",
    "I once ate a clock. It was very time consuming.",
    "What do you call a belt made of watches? A waist of time!",
    "Why did the music note go to the party? It wanted to have a good time!",
    "I'm no photographer, but I can picture us together.",
    "What do you call a sleeping T-Rex? A dino-snore!",
    "Why did the computer go to lunch? It wanted to grab a byte!",
    "I used to be a personal trainer. Then I gave two weak notice.",
    "What do you call a sad strawberry? A blueberry!",
    "Why do bananas have to wear sunscreen? Because they peel!",
    "I used to hate math but then I realized decimals have a point.",
    "What do you call a nervous javelin thrower? Shakespeare!",
    "Why did the orange stop rolling down the hill? It ran out of juice!",
    "I used to be a banker, but I lost interest.",
    "What do you call a cow with a twitch? Beef jerky!",
    "Why did the tree go to the barbershop? It needed a trim!",
    "I'm reading a book about teleportation. It's bound to get me somewhere.",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the chicken go to the séance? To get to the other side!",
    "I used to be a tap dancer, but I fell into the sink.",
    "What do you call a magician dog? A Labracadabrador!",
    "Why did the clock get in trouble at school? For tocking too much!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "What do you call a fake spaghetti? An impasta!",
    "Why did the tomato blush? It saw the salad dressing!",
    "I used to work at a fire hydrant factory, but you couldn't park anywhere.",
    "What do you call a bear with no ears? B!",
    "Why did the computer catch a cold? It left its Windows open!",
    "I used to be addicted to soap. I'm clean now.",
    "What do you call a snowman in the summer? A puddle!",
    "Why did the duck cross the road? To prove he wasn't a chicken!",
    "I'm reading a book on the history of WD-40. It's non-friction.",
    "What do you call a pig who knows karate? A pork chop!",
    "Why did the math teacher open a window? For some fresh air-ithmetic!",
    "I used to be a personal banker, but I lost interest.",
    "What do you call a bee that can't make up its mind? A maybe!",
    "Why did the ghost go to the party? To boo-gie!",
    "I don't trust stairs because they're always up to something.",
    "What do you call a crocodile wearing a vest? An investigator!",
    "Why did the opera singer go to the bank? To check her aria!",
    "I used to be a road, but I went off on a different path.",
    "What do you call a dinosaur with a sore back? A stegosore-us!",
    "Why did the music note get bad grades? It kept getting sharp and flat!",
    "I'm great at sleeping. I can do it with my eyes closed.",
    "What do you call a magic dog? A Labracadabrador!",
    "Why did the student eat his homework? His teacher said it was a piece of cake!",
    "I used to be a teacher, but I didn't have enough class.",
    "What do you call a cow in an earthquake? A milkshake!",
    "Why did the belt go to jail? For holding up pants!",
    "I tried to come up with a carpentry pun, but nothing wood work.",
    "What do you call a snobbish prisoner going down stairs? A condescending con descending!",
    "Why did the bicycle stand by itself? It was two-tired!",
    "I used to be a train conductor, but I got sidetracked.",
    "What do you call a bee who's having a bad hair day? A frizz-bee!",
    "Why did the egg hide? It was a little chicken!",
    "I'd tell you a chemistry joke, but I wouldn't get a reaction.",
    "What do you call a story about a broken pencil? Pointless!",
    "Why did the clock get promoted? It worked around the clock!",
    "I used to know a guy who collected candy canes. They were all in mint condition.",
    "What do you call a pile of kittens? A meow-ntain!",
    "Why did the nurse need a red pen? In case she needed to draw blood!",
    "I'm friends with all the planets. We have stellar relationships.",
    "What do you call a baby monkey? A chimp off the old block!",
    "Why did the skeleton go to the party alone? He had no body to go with!",
    "I used to be a lifeguard, but I couldn't keep my head above water.",
    "What do you call a really cold dog? A chili dog!",
    "Why did the tree fail the test? It kept getting stumped!",
    "I used to collect maps, but I've lost my way.",
    "What do you call a lazy doctor? Dr. Do-little!",
    "Why did the cookie go to the nurse? Because it felt crummy!",
    "I used to have a job crushing cans. It was soda pressing.",
    "What do you call a fish without eyes? Fsh!",
    "Why did the lamp look sad? It was a little light-headed!",
    "I gave all my dead batteries away today, free of charge.",
    "What do you call a priest who sleepwalks? A roamin' Catholic!",
    "Why did the baker stop making donuts? He got tired of the hole thing!",
    "I used to collect coins, but I spent them all.",
    "What do you call a train that sneezes? Achoo-choo train!",
    "Why did the computer squeak? Someone stepped on its mouse!",
    "I don't trust atoms. They make up everything!",
    "What do you call a witch at the beach? A sand-witch!",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one!",
    "I used to work in a blanket factory, but it folded.",
    "What do you call a cow with no legs? Ground beef!",
    "Why did the music teacher go to jail? She got in treble!",
    "I'm writing a book about hurricanes. It's blowing up!",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "Why did the farmer plant light bulbs? He wanted a power plant!",
    "I used to hate beards. Then they grew on me.",
    "What do you call a funny mountain? Hill-arious!",
    "Why did the book join the police? It wanted to go undercover!",
    "I'm trying to organize a hide and seek tournament, but good players are hard to find.",
    "What do you call a pig that does karate? A pork chop!",
    "Why did the banana go to the hospital? It wasn't peeling well!",
    "I used to work for a company that made scales, but I had to weigh my options.",
    "What do you call a deer with no eyes? No idea!",
    "Why did the guitar go to the doctor? It had string fever!",
    "I was going to tell a time travel joke, but you didn't like it.",
    "What do you call a cow that just had a baby? De-calf-inated!",
    "Why did the envelope go to school? To get a letter education!",
    "I used to be a plastic surgeon, but I folded under pressure.",
    "What do you call a chicken at the North Pole? Lost!",
    "Why did the orange use sunscreen? It didn't want to peel!",
    "I'm not addicted to brake fluid. I can stop any time!",
    "What do you call a cat who likes to bowl? An alley cat!",
    "Why did the watch break up with the clock? Their relationship was overwound!",
    "I used to play tennis, but I quit. It wasn't really my racket.",
    "What do you call a moose with no name? Anonymoose!",
    "Why did the coffee taste like mud? It was just ground!",
    "I used to work at a fire hydrant factory. Couldn't park anywhere near the place.",
    "What do you call a zombie who cooks stir fry? Dead man wok-ing!",
    "Why did the rocket break up with the satellite? It needed more space!",
    "I used to be a banker, but I lost interest.",
    "What do you call a sleeping dinosaur? A dino-snore!",
    "Why did the window break up with the door? It saw right through him!",
    "I was going to tell a pizza joke, but it was too cheesy.",
    "What do you call a happy cowboy? A jolly rancher!",
    "Why did the mushroom get invited to parties? Because he's a fungi!",
    "I used to be a shoe salesman, till they gave me the boot.",
    "What do you call a line of men waiting to get haircuts? A barberqueue!",
    "Why did the calendar break up with the clock? Their days were numbered!",
    "I'm trying to learn sign language. It's pretty handy!",
    "What do you call a sad coffee? A depresso!",
    "Why did the tree get in trouble? For being shady!",
    "I used to have a job crushing cans. It was soda pressing.",
    "What do you call a pile of cats? A meowtain!",
    "Why did the DJ go to the doctor? He had a slipped disc!",
    "I told my wife she should do lunges. That would be a big step forward.",
    "What do you call a can opener that doesn't work? A can't opener!",
    "Why did the crab never share? He was shellfish!",
    "I used to be indecisive, but now I'm not so sure.",
    "What do you call a factory that makes okay products? Satisfactory!",
    "Why did the computer catch cold? It left its Windows open!",
    "I'm friends with 25 letters of the alphabet. I don't know Y.",
    "What do you call a cow on a trampoline? A milk shake!",
    "Why did the scarecrow win an award? He was out standing in his field!",
    "I used to be a banker, but then I lost interest.",
    "What do you call two birds in love? Tweet-hearts!",
    "Why did the stadium get hot? Because all the fans left!",
    "I tried to make a belt out of watches, but it was a waist of time.",
    "What do you call a rabbit with fleas? Bugs Bunny!",
    "Why did the cellphone get glasses? It lost all its contacts!",
    "I used to collect stamps, but then I ran out of licks.",
    "What do you call a snobby prisoner going downstairs? A condescending con descending!",
    "Why did the skeleton go to the party alone? He had no body to go with!",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "What do you call a computer that sings? A-Dell!",
    "Why did the bubble gum cross the road? It was stuck to the chicken's foot!",
    "I used to work at a orange juice factory, but I got canned.",
    "What do you call a boomerang that won't come back? A stick!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "I'm not a fan of spring cleaning. I'm barely a fan of spring acknowledging.",
    "What do you call a three-humped camel? Pregnant!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I used to be a doctor, but I didn't have the patience.",
    "What do you call an elephant that doesn't matter? An irrelephant!",
    "Why did the restaurant owner go to the doctor? He had a bad case of gastritis!",
    "I'm on a whiskey diet. I've lost three days already!",
    "What do you call a baby bear with no teeth? A gummy bear!",
    "Why did the gym close down? It just didn't work out!",
    "I used to be a math teacher, but I couldn't count on my students.",
    "What do you call a cow that can't moo? A milk dud!",
    "Why did the banana go to the party? Because it was a-peeling!",
    "I would tell you a joke about paper, but it's tearable.",
    "What do you call a fish wearing a crown? King of the sea!",
    "Why did the photo go to jail? It was framed!",
    "I used to work at a calendar factory but I got fired for taking days off.",
    "What do you call a magician who lost his magic? Ian!",
    "Why did the computer go to the beach? To surf the web!",
    "I'm not lazy, I'm just very relaxed.",
    "What do you call a cow with two legs? Lean beef!",
    "Why did the ocean break up with the pond? It was too shallow!",
    "I used to work at a donut shop, but I got tired of the hole thing.",
    "What do you call a snowman with a six pack? An abdominal snowman!",
    "Why did the astronaut break up with his girlfriend? He needed space!",
    "I'm terrified of elevators. I'm taking steps to avoid them.",
    "What do you call a deer with no eyes and no legs? Still no idea!",
    "Why did the candle break up with the match? It found someone brighter!",
    "I used to work at a mirror factory. I could really see myself there.",
    "What do you call a dinosaur that never gives up? Try-try-try-ceratops!",
    "Why did the broom get promoted? It swept the competition!",
    "I tried to write a poem about air. It was hard to put words to wind.",
    "What do you call a penguin in the desert? Lost!",
    "Why did the drum take a nap? It was beat!",
    "I used to collect maps, but I lost my way.",
    "What do you call a teacher who never farts? A private tutor!",
    "Why did the leaf go to the doctor? It was feeling green!",
    "I'm so bright my mom calls me son.",
    "What do you call a shoe made of a banana? A slipper!",
    "Why did the sun go to school? To get brighter!",
    "I used to hate facial hair, but it grew on me.",
    "What do you call a dinosaur that smashes everything? Tyrannosaurus Wrecks!",
    "Why did the golfer cry? He was going through a rough patch!",
    "I tried to catch some fog earlier. I mist.",
    "What do you call a lazy baby kangaroo? A pouch potato!",
    "Why did the skeleton go to the barbecue? To get another rib!",
    "I used to be a personal trainer. Then I gave my too weak notice.",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the cookie cry? Because his mom was a wafer so long!",
    "I would tell you a chemistry joke, but all the good ones argon.",
    "What do you call a horse that lives next door? A neigh-bor!",
    "Why did the traffic light turn red? You would too if you had to change in the middle of the street!",
    "I used to be a shoe salesman, but I didn't fit in.",
    "What do you call a pile of kittens? A meowtain!",
    "Why did the teddy bear say no to dessert? She was stuffed!",
    "I'm reading a book about mazes. I got lost in it.",
    "What do you call an old snowman? Water!",
    "Why did the laptop go to the doctor? It had a virus!",
    "I used to work at a butcher shop, but I had to cut back.",
    "What do you call a train carrying bubblegum? A chew-chew train!",
    "Why did the scarecrow become a therapist? He was outstanding in his field!",
    "I don't play soccer because I enjoy it. I'm just doing it for kicks!",
    "What do you call a grumpy cow? Moody!",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it!",
    "I used to be addicted to time travel. But that's all in the past now.",
    "What do you call a fake pasta? An impasta!",
    "Why did the orange lose the race? It ran out of juice!",
    "I told my wife she was overreacting. She just rolled her eyes and left me on read.",
    "What do you call a cat who loves bowling? An alley cat!",
    "Why did the baker go to therapy? He had too many emotional turnovers!",
    "I used to be afraid of hurdles, but I got over it.",
    "What do you call a group of musical whales? An orca-stra!",
    "Why did the tomato go out with a prune? Because it couldn't find a date!",
    "I'm not a complete idiot. Some parts are missing.",
    "What do you call a bear in the rain? A drizzly bear!",
    "Why did the egg get thrown out of class? For telling too many yolks!",
    "I used to play sports. Then I realized I could buy trophies.",
    "What do you call a dinosaur that knows a lot of words? A thesaurus!",
    "Why did the calendar go to therapy? It had too many issues with its dates!",
]

def get_random_joke() -> str:
    """Get a random dad joke."""
    return random.choice(DAD_JOKES)

def get_joke_by_index(index: int) -> str:
    """Get a specific joke by index."""
    return DAD_JOKES[index % len(DAD_JOKES)]

def get_total_jokes() -> int:
    """Get total number of jokes."""
    return len(DAD_JOKES)
